version: 2.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - checkout

      - run:
          name: Install Docker CLI
          command: |
            curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
            echo "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
            sudo apt-get update
            sudo apt-get install -y docker-ce-cli

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - run:
          name: Build and push AutoNav
          command: |
            docker build -t jatinvpatil/autoserve:latest -f autoserve.Dockerfile .
            docker push jatinvpatil/autoserve:latest

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
